config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  # Below line will map any request to get the about page to the about action of the simple_pages controller
  get 'simple_pages/about'
  get 'simple_pages/contact'

  get 'simple_pages/index'
  # Thanks to this routes.rb and below line, Rails will map requests to the root of the App to the to the landing_page action of the simple_pages controller
  root 'simple_pages#landing_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'simple_pages/thank_you'

  post 'payments/create'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  validates :name, length: { minimum: 2 }
  validates :description, length: { maximum: 200 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  self.per_page = 4

  def self.search(search_term)
    if Rails.env.production?
      Product.where("name ilike ?", "%#{search_term}%")
    else
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    # byebug
    if params[:q]
      search_term = params[:q]
      # @products = Product.search(search_term)
      @products = Product.search(search_term).paginate(page: params[:page], per_page: 5)
    else
      # @products = Product.all
      @products = Product.paginate(page: params[:page], per_page: 5)
      logger.debug "Length of the Product table to be displayed: #{@products.length}"
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div>
      <hr>
      <p>
        <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <% if signed_in? && current_user.admin? %>
          <%= link_to 'Destroy', product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "badge badge-danger" %>
        <% end %>
      </p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= "Rating: #{comment.rating}/5" %></p>

      <p><%= comment.body %></p>
    </div>
  <% end %>
</div>

<script>
  $(document).on('turbolinks:load', function(){
    $('.rated').raty({
      starHalf: '<%= asset_path 'star-half.png' %>',
      starOff: '<%= asset_path 'star-off.png' %>',
      starOn: '<%= asset_path 'star-on.png' %>',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
  });
</script>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <form>
    <div class="form-group row">
      <%= form.label :name, class: "col-sm-2 col-form-label" %>
      <%= form.text_field :name, class: "form-control col-sm-4", placeholder: "Name" %>
    </div>

    <div class="form-group row">
      <%= form.label :description, class: "col-sm-2 col-form-label" %>
      <%= form.text_area :description, class: "form-control col-sm-4", placeholder: "Description" %>
    </div>

    <div class="form-group row">
      <%= form.label :image_url, class: "col-sm-2 col-form-label" %>
      <%= form.text_field :image_url, class: "form-control col-sm-4", placeholder: "Image url" %>
    </div>

    <div class="form-group row">
      <%= form.label :price, class: "col-sm-2 col-form-label" %>
      <%= form.text_field :price, class: "form-control col-sm-4", placeholder: "Price" %>
    </div>

    <div class="actions">
      <%= form.submit :Submit, class: "btn btn-primary" %>
    </div>
  </form>
  <br>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%# form_for([@product, @product.comments.build]) do |f| %>
  <%# Below is a test of AJAX implementation with Rails 6 but did not work see comments %>

  <%= form_with(model: [@product, @product.comments.build], id: "new_comment") do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body, class: "form-control" %>
    </p>

    <p>
      <div class="rating">Your rating: </div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

<script>
  $(document).on('turbolinks:load', function(){
    $('.rating').raty({
      starHalf: '<%= "#{image_path('star-half.png')}" %>',
      starOff: '<%= "#{image_path('star-off.png')}" %>',
      starOn: '<%= "#{image_path('star-on.png')}" %>',
      scoreName: 'comment[rating]'
    });
  });
</script>

app/views/products/_product.html.erb
<div class="col-sm-4 col-lg-2">
  <% cache product do %>
    <div class="card w-120">
      <%= image_tag(product.image_url, class: "img-fluid") unless product.image_url.nil? %>
      <div class="card-body"><% logger.debug "Product id: #{product.id}" %>
        <h5 class="card-title"><%= product.name %></h5><% logger.debug "Product name: #{product.name}" %>
        <p class="card-text"><%= product.description %></p><% logger.debug "Product description: #{product.description}" %>
        <p class="card-text"><%= product.price %> Euros</p><% logger.debug "Product price: #{product.price}" %>
        <%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div><!-- end card -->
  <% end %>
</div>

app/views/products/edit.html.erb
<section class="container">

  <h1>Editing Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>

</section>

app/views/products/index.html.erb
<section class="container">

  <h1>Products</h1>

  <div class="container-fluid">

    <div class="row justify-content-center">
      <% cache @products do %>
        <%= render @products %>
      <% end %>
    </div><!-- end row -->

    <div class="row justify-content-center flickr_pagination">
      <%= will_paginate @products %>
    </div>

    <br>
    <%= link_to 'New Product', new_product_path %>

  </div><!-- end conatiner-fluid -->
</section>

app/views/products/new.html.erb
<section class="container">

  <h1>New Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path %>

</section>

app/views/products/show.html.erb
<section class="container">
  <div class="row">
    <% cache @product do %>
      <div class="card mx-auto col-md-4">
        <div><%= image_tag(@product.image_url, class: "img-fluid img-responsive img-zoom", data_zoom_image: @product.image_url) unless @product.image_url.nil? %></div>

        <div class="card-body">
          <h5 class="card-title">
            <strong>Name:</strong>
            <%= @product.name %>
          </h5>
          <p class="card-text">
            <strong>Description:</strong>
            <%= @product.description %>
          </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <strong>Average Rating: </strong>
            <div class="rated" data-score="<%= @product.average_rating %>"></div>
          </li>
          <li class="list-group-item">
            <strong>Price:</strong>
            <%= @product.price %> Euros
          </li>
          <li class="list-group-item">
            <%= form_with(url: '/payments/create') do |form| %>
              <%= hidden_field_tag(:product_id, @product.id) %>
              <%= render partial: "shared/stripe_checkout_button" %>
            <% end %>
          </li>
          <li class="list-group-item">
            <strong>Image url:</strong>
            <%= @product.image_url %>
          </li>
          <li class="list-group-item">
            <%= render 'new_comment' %>
          </li>
          <li class="list-group-item">
            <%= render 'comments' %>
            <div class="row justify-content-md-center flickr_pagination">
              <%= will_paginate @comments %>
            </div>
          </li>
        </ul>
        <div class="card-body text-center">
          <%= link_to 'Edit', edit_product_path(@product) %> |
          <%= link_to 'Back', products_path %>
        </div>
      </div>
    <% end %>
  </div><!-- end row -->

</section>

<script>
  $('.img-zoom').elevateZoom(
    {
    zoomType				: "inner",
    cursor: "crosshair"
    }

  );
</script>