config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  # Below line will map any request to get the about page to the about action of the simple_pages controller
  get 'simple_pages/about'
  get 'simple_pages/contact'

  get 'simple_pages/index'
  # Thanks to this routes.rb and below line, Rails will map requests to the root of the App to the to the landing_page action of the simple_pages controller
  root 'simple_pages#landing_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'simple_pages/thank_you'

  post 'payments/create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ethnics &amp; Silver</title>

    <!-- Link to Boostrap CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Links to our CSS and JavaScript files (Asset Pipeline) -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light sticky-top">
      <div class="navbar-brand">
        <%= link_to image_tag("logo_img.png", height: "30"), simple_pages_index_path, class: "img-fluid" %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
            <%= link_to "Home", simple_pages_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Products", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Orders", orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Users", users_path, class: "nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to('Login', new_user_session_path, class: "nav-link") %>
          </li>
          <% end %>
        </ul>

        <ul class="navbar-nav">

          <div class="form-inline">

          <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
            <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control", placeholder: "Search for" %>

            <%= form.submit 'Search', class: "btn btn-primary" %>

          <% end %>
          </div>

        </ul>

      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-primary alert-dismissible" role="notice"><%= notice %><!-- to print out notices -->
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert"><%= alert %><!-- to print out alerts -->
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>

    <%= yield %>

    <footer class="bottom">
      <hr>
      <div class="container-fluid">
        <p>&copy; 2020 Ethnics &amp; Silver</p>
      </div>
    </footer>

  <!-- <script>
    $( "div.alert" ).delay( 2000 ).fadeOut( 1000 );
  </script> -->

  </body>
</html>